<?php
return [
    'global' => [
        'site_logo' => 'Nom de la marque',
        'footer_tagline' => 'Texte du footer',
        'contact_phone' => 'Téléphone',
        'contact_email' => 'Email',
        'contact_instagram' => 'Lien Instagram',
        'contact_location' => 'Localisation',
    ],
    'home' => [
        'home_badge' => 'Hero - Badge',
        'home_hero_title' => 'Hero - Titre',
        'home_hero_text' => 'Hero - Paragraphe',
        'home_primary_cta' => 'Hero - Bouton principal',
        'home_secondary_cta' => 'Hero - Bouton secondaire',
        'home_intro_heading' => 'Présentation - Titre',
        'home_intro_subtitle' => 'Présentation - Sous-titre',
        'home_intro_card1_title' => 'Présentation - Carte 1 titre',
        'home_intro_card1_text' => 'Présentation - Carte 1 texte',
        'home_intro_card2_title' => 'Présentation - Carte 2 titre',
        'home_intro_card2_text' => 'Présentation - Carte 2 texte',
        'home_intro_card3_title' => 'Présentation - Carte 3 titre',
        'home_intro_card3_text' => 'Présentation - Carte 3 texte',
        'home_signature_heading' => 'Signature - Titre',
        'home_signature_subtitle' => 'Signature - Sous-titre',
        'home_signature_points' => 'Signature - Blocs (ligne = titre|texte)',
        'home_signature_primary_cta' => 'Signature - CTA principal',
        'home_signature_secondary_cta' => 'Signature - CTA secondaire',
        'home_short_heading' => 'Formations courtes - Titre',
        'home_short_subtitle' => 'Formations courtes - Sous-titre',
        'home_short_modules' => 'Formations courtes - Modules (ligne = titre|texte)',
        'home_short_catalog_cta' => 'Formations courtes - CTA catalogue',
        'home_short_page_cta' => 'Formations courtes - CTA interne',
        'home_why_heading' => 'Pourquoi - Titre',
        'home_why_subtitle' => 'Pourquoi - Sous-titre',
        'home_why_points' => 'Pourquoi - Points (ligne = titre|texte)',
        'home_testimonials_heading' => 'Témoignages - Titre',
        'home_testimonials_subtitle' => 'Témoignages - Sous-titre',
        'home_testimonials' => 'Témoignages - Liste (ligne = citation|Prénom)',
        'home_contact_title' => 'Contact - Titre',
        'home_contact_text' => 'Contact - Texte',
        'home_contact_primary_cta' => 'Contact - CTA principal',
        'home_contact_secondary_cta' => 'Contact - CTA secondaire',
    ],
    'formation-signature' => [
        'signature_hero_title' => 'Hero - Titre',
        'signature_hero_text' => 'Hero - Paragraphe',
        'signature_hero_primary_cta' => 'Hero - CTA principal',
        'signature_hero_secondary_cta' => 'Hero - CTA secondaire',
        'signature_pillars_title' => 'Piliers - Titre',
        'signature_pillars_subtitle' => 'Piliers - Sous-titre',
        'signature_pillars' => 'Piliers (ligne = titre|texte)',
        'signature_program_title' => 'Programme - Titre',
        'signature_program_subtitle' => 'Programme - Sous-titre',
        'signature_program_blocks' => 'Programme - Blocs (ligne = titre|puces séparées par ;) ',
        'signature_support_title' => 'Accompagnement - Titre',
        'signature_support_cards' => 'Accompagnement - Cartes (ligne = titre|texte)',
        'signature_results_title' => 'Résultats - Titre',
        'signature_results_points' => 'Résultats - Points (ligne = titre|texte)',
        'signature_testimonials_title' => 'Témoignages - Titre',
        'signature_testimonials' => 'Témoignages - Liste (ligne = citation|Prénom)',
        'signature_pricing_text' => 'Encart tarif - Texte',
        'signature_pricing_cta_primary' => 'Encart tarif - CTA principal',
        'signature_pricing_cta_secondary' => 'Encart tarif - CTA secondaire',
    ],
    'formations-courtes' => [
        'short_intro_title' => 'Intro - Titre',
        'short_intro_text' => 'Intro - Texte',
        'short_modules_heading' => 'Modules - Titre',
        'short_modules_list' => 'Modules - Liste (ligne = titre|texte)',
        'short_infos_heading' => 'Infos pratiques - Titre',
        'short_infos_points' => 'Infos pratiques - Points (ligne = titre|texte)',
        'short_cta_text' => 'CTA - Texte',
    ],
    'temoignages' => [
        'testimonials_intro_title' => 'Intro - Titre',
        'testimonials_intro_text' => 'Intro - Texte',
        'testimonials_gallery' => 'Témoignages - Liste (ligne = citation|Prénom)',
        'testimonials_cta_text' => 'CTA - Texte',
    ],
    'contact' => [
        'contact_page_title' => 'Hero - Titre',
        'contact_page_intro' => 'Hero - Intro',
        'contact_info_title' => 'Bloc info - Titre',
        'contact_info_text' => 'Bloc info - Paragraphe',
        'contact_info_list' => 'Bloc info - Lignes (ligne = label|valeur|lien)',
        'contact_form_title' => 'Formulaire - Titre',
        'contact_form_text' => 'Formulaire - Texte',
        'contact_form_subject' => 'Formulaire - Sujet email',
        'contact_form_button' => 'Formulaire - Bouton',
    ],
    'legal' => [
        'legal_content' => 'Mentions légales & CGV (HTML autorisé)'
    ],
];
